services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postus
      PGUSER: postus
      POSTGRES_PASSWORD: passus
      POSTGRES_DB: AcademicPerformanceDatabase
      PGDATA: /data/postgres
    ports:
      - "1234:5432"
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postus", "-d", "AcademicPerformanceDatabase" ]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    depends_on:
      - db
    image: tomcat:11.0.6-jdk21-temurin-noble
    ports:
      - "8082:8080"
    volumes:
      - ./target/RestServiceHomework-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    networks:
      - db
networks:
  db:
    driver: bridge

volumes:
  db: